In [ ]:
#IMPORTING LIBRARIES AND DATA
import numpy as np 
import pandas as pd 
import plotly.express as px 
from textblob import TextBlob 
df = pd.read_csv(r"C:\Users\samyu\Downloads\netflix_titles.csv.zip")

In [ ]:
#Checking number of rows and columns in data
df.shape

(8807, 12)

In [ ]:
#Checking content available in Dataset
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [108]:
#checking columns name of dataset
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

Taking the count of ratings available

In [73]:
x = df.groupby("rating").size().reset_index(name="counts")

Creating the Piechart based on Content rating

In [74]:
pieChart = px.pie(
    x,
    values='counts',
    names='rating',
    title='Distribution of Content Ratings on Netflix'
)

pieChart.show()

Analyzing the top 5 Directors on Netflix

In [75]:
#Replace missing director names
df["director"] = df["director"].fillna("directors not specified")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,directors not specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,directors not specified,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,directors not specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [76]:
#Create empty dataframe
directors_list = pd.DataFrame()

In [77]:
directors_list

Empty DataFrame
Columns: []
Index: []

In [78]:
#Split the directors column
directors_list= df["director"].str.split(',',expand=True).stack()  #stack converts columns to row

In [79]:
directors_list

0     0            Kirsten Johnson
1     0    directors not specified
2     0            Julien Leclercq
3     0    directors not specified
4     0    directors not specified
                    ...
8802  0              David Fincher
8803  0    directors not specified
8804  0            Ruben Fleischer
8805  0               Peter Hewitt
8806  0                Mozez Singh
Length: 9612, dtype: object

In [80]:
directors_list= directors_list.to_frame()      
directors_list                                #to_frame() Convert this Series into a table (DataFrame).

                              0
0    0          Kirsten Johnson
1    0  directors not specified
2    0          Julien Leclercq
3    0  directors not specified
4    0  directors not specified
...                         ...
8802 0            David Fincher
8803 0  directors not specified
8804 0          Ruben Fleischer
8805 0             Peter Hewitt
8806 0              Mozez Singh

[9612 rows x 1 columns]

In [81]:
## Rename the column heading because before it was 0

directors_list.columns = ["director"]
directors_list

                       director
0    0          Kirsten Johnson
1    0  directors not specified
2    0          Julien Leclercq
3    0  directors not specified
4    0  directors not specified
...                         ...
8802 0            David Fincher
8803 0  directors not specified
8804 0          Ruben Fleischer
8805 0             Peter Hewitt
8806 0              Mozez Singh

[9612 rows x 1 columns]

In [82]:
directors = directors_list.groupby("director").size().reset_index(name="total count")
directors

                       director  total count
0                Aaron Moorhead            2
1                   Aaron Woolf            1
2      Abbas Alibhai Burmawalla            1
3              Abdullah Al Noor            1
4           Abhinav Shiv Tiwari            1
...                         ...          ...
5116                Çagan Irmak            1
5117           Ísold Uggadóttir            1
5118        Óskar Thór Axelsson            1
5119           Ömer Faruk Sorak            2
5120               Şenol Sönmez            2

[5121 rows x 2 columns]

In [83]:
## Keep only rows where Director is NOT equal to 'Director not specified'
directors= directors[directors!="Director not specified"]
directors

                       director  total count
0                Aaron Moorhead            2
1                   Aaron Woolf            1
2      Abbas Alibhai Burmawalla            1
3              Abdullah Al Noor            1
4           Abhinav Shiv Tiwari            1
...                         ...          ...
5116                Çagan Irmak            1
5117           Ísold Uggadóttir            1
5118        Óskar Thór Axelsson            1
5119           Ömer Faruk Sorak            2
5120               Şenol Sönmez            2

[5121 rows x 2 columns]

In [84]:
#Arrange directors based on Total Count from highest to lowest.
directors = directors.sort_values(by=['total count'], ascending=False)

In [85]:
top5Directors = directors.head()
top5Directors

                     director  total count
5108  directors not specified         2634
4020            Rajiv Chilaka           22
261                 Jan Suter           18
4067              Raúl Campos           18
3235             Marcus Raboy           16

Analyzing the top 5 Actors on Netflix

In [86]:
#Replace missing cast values
df['cast'] = df["cast"].fillna("no cast specified")

In [87]:
#Create empty dataframe
cast_df = pd.DataFrame()

In [88]:
#Split multiple actors
cast_df = df['cast'].str.split(',', expand=True).stack()

In [89]:
#Convert Series → DataFrame
cast_df = cast_df.to_frame()

In [90]:
#Rename column
cast_df.columns = ['actor']

In [91]:
#remove unwanted rows
actors = cast_df.groupby(['actor']).size().reset_index(name='Total Count')

In [92]:
#Remove fake values
actors = actors[actors.actor != 'no cast specified']

In [93]:
#Sort highest → lowest
actors = actors.sort_values(by=['Total Count'], ascending=False)

In [94]:
#Get top 5 actors
top5Actors = actors.head()

In [95]:
#Sort again for chart appearance
top5Actors = top5Actors.sort_values(by=['Total Count'])

In [96]:
#Create bar chart
barChart2 = px.bar(
    top5Actors,
    x='Total Count',
    y='actor',
    title='Top 5 Actors on Netflix'
)

In [97]:
#show chart
barChart2.show()

Sentiment Analysis of Netflix Content

In [98]:
#Select needed columns
df3 = df[['release_year', 'description']]

In [99]:
#Rename columns
df3 = df3.rename(columns={
    'release_year':'Release Year',
    'description':'Description'
})

In [101]:
#Loop through each row
for index, row in df3.iterrows():
  d=row['Description']
  testimonial = TextBlob(d)
  p = testimonial.sentiment.polarity
  if p==0:
    sent = 'Neutral'
  elif p>0:
    sent = 'Positive'
  else:
    sent = 'Negative'
  df3.loc[[index, 2], 'Sentiment']=sent

In [103]:
#Save sentiment into dataframe
df3.loc[index, 'Sentiment'] = sent

In [104]:
#Count sentiments per year
df3 = df3.groupby(
    ['Release Year', 'Sentiment']
).size().reset_index(name='Total Count')

In [105]:
#Filter years after 2005
df3 = df3[df3['Release Year'] > 2005]

In [107]:
#Create visualization
barGraph = px.bar(
    df3,
    x="Release Year",
    y="Total Count",
    color="Sentiment",
    title="Sentiment Analysis of Content on Netflix"
)
barGraph.show()